questionnairepro/urls.py
from django.conf.urls import url
from django.contrib import admin
from app01 import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', views.login),
    url(r'^stu_login/$', views.stu_login),
    url(r'^index/$', views.index),
    url(r'^stu_index/$', views.stu_index),
    url(r'^del_question/$', views.del_question),
    url(r'^editor/questionnaire/(?P<questionnaire_id>\d+)', views.editor_ques),
    url(r'^student/evaluate/(\d+)/(\d+)/', views.fill_naire),

]

app01/models.py
from django.db import models

# Create your models here.

class Userifo(models.Model):
    '''用户表'''
    username=models.CharField(max_length=32)
    password=models.CharField(max_length=32)

    def __str__(self):
        return self.username

class ClassList(models.Model):
    """
    班级表
    """
    title = models.CharField(max_length=32)

    def __str__(self):
        return self.title


class Student(models.Model):
    """
    学生表
    """
    user = models.CharField(max_length=32)
    pwd = models.CharField(max_length=32)
    cls = models.ForeignKey(to="ClassList")

    def __str__(self):
        return self.user


class Questionnaire(models.Model):
    """
    问卷表
    """
    title = models.CharField(max_length=64)
    cls = models.ForeignKey(to="ClassList")
    creator = models.ForeignKey(to="Userifo")

    def __str__(self):
        return self.title


class Question(models.Model):
    """
    问题
    """
    questionnaire=models.ForeignKey(to="Questionnaire")
    caption = models.CharField(max_length=64)
    question_types = (
        (1,'打分(1~10)'),
        (2,'单选'),
        (3,'评价'),
    )
    type = models.IntegerField(choices=question_types)

    def __str__(self):
        return self.caption


class Option(models.Model):
    """
    单选题的选项
    """
    name = models.CharField(verbose_name='选项名称',max_length=32)
    score = models.IntegerField(verbose_name='选项对应的分值')
    question = models.ForeignKey(to="Question")

    def __str__(self):
        return self.name


class Answer(models.Model):
    """
    回答
    """
    student = models.ForeignKey(to="Student")
    question = models.ForeignKey(to="Question")


    val = models.IntegerField(null=True,blank=True)
    oid=models.IntegerField(null=True,blank=True)
    content = models.CharField(max_length=255,null=True,blank=True)

templates/editor_ques.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>编辑问卷</title>
    <link rel="stylesheet" href="/static/bootstrap-3.3.7-dist/css/bootstrap.min.css">
    <style>
        .question{background-color: #ebebeb;}
        .hide{
            display: none;
        }
        ol {
            padding: 0;
            list-style: none;
            counter-reset: sectioncounter
        }

        ol > li:before {
            content: '问题' counter(sectioncounter) ':';
            counter-increment: sectioncounter;
            font-size: 18px;
            color: #d4d4d4;
        }

        ol > li:nth-of-type(odd) {
            background-color: #f9f9f9;
        }


    </style>
</head>
<body>
<h2>编辑问卷表题目</h2>
<div class="container">
     <div >
     <p> <button class="btn btn-primary add_question">添加</button> <button class="btn btn-success" id="btn_save">保存</button></p>
        <ol id="questions" questionnaire_id="{{ questionnaire_id }}">
            {% for dict in data %}
            <li class="question"  qid="{{ dict.qid }}">
            <span class="glyphicon glyphicon-remove pull-right del_question"></span>
            <div class="row">
               <div class="col-md-1 col-md-offset-1">
                <p>问题：</p>
            </div>
            <div class="col-md-7 title">
                <p>{{ dict.form.caption }}</p>
            </div>

            </div>
            <div class="row">
               <div class="col-md-1 col-md-offset-1">
                <p>类型：</p>
            </div>
            <div class="col-md-8">
                {{ dict.form.type }} <span class="glyphicon glyphicon-plus {{ dict.class }} add_option" style="color:blue;">添加选项</span>
                <div >
                   {% for option in dict.options %}
                    <p option_id="{{ option.option_id }}" class="option">内容：{{ option.form.name }}分值：{{ option.form.score }}
                       <span class="glyphicon glyphicon-remove del_option"></span></p>

                    {% endfor %}
                </div>


            </div>


            </div>
            </li>
            {% endfor %}
            
            
        </ol>
    </div>






</div>


<script src="/static/jquery-3.2.1.min.js"></script>
<script src="/static/jquery.cookie.js"></script>
<script>
    //添加问题事件
    $(document).on('click',".add_question",function () {
       s='<li class="question" qid> <span class="glyphicon glyphicon-remove pull-right del_question"></span> <div class="row"> <div class="col-md-1 col-md-offset-1"> <p>问题：</p> </div> <div class="col-md-7"> <p><textarea name="caption" cols="80" rows="2" class="form-control" maxlength="64" required="" id="id_caption"></textarea></p> </div> </div> <div class="row"> <div class="col-md-1 col-md-offset-1"> <p>类型：</p> </div><div class="col-md-8"> <select name="type" class="select_type" required="" id="id_type"> <option value="" selected="">---------</option> <option value="1">打分(1~10)</option> <option value="2">单选</option> <option value="3">评价</option> </select> <span class="glyphicon glyphicon-plus hide add_option" style="color:blue;">添加选项</span> <div> </div> </div> </div> </li>'
        $("#questions").append(s)
    });

   //select选项改变时的事件
    $(document).on('change','.select_type',function () {

        if ($(this).val()==2){
            $(this).next().removeClass("hide");

        }
        else {
           $(this).parent().children().last().children().remove();
           $(this).next().addClass("hide")
        }
    });

    //删除问题事件
    $(document).on('click','.del_question',function () {
        var this_tag=$(this)
        if (this_tag.parent().attr("qid") && this_tag.parent().attr("qid") != 'None'){
           $.ajax({
               url:"/del_question/?qid="+$(this).parent().attr("qid"),
               success:function (data) {
                   var data=JSON.parse(data);
                   if(data["flag"]){
                      this_tag.parent().remove()
                   }
               }
           })

        }
         else {
              this_tag.parent().remove()
            }

    });


    //添加选项的事件
    $(document).on('click','.add_option',function () {
      s='<p option_id class="option">内容：<input type="text" name="name" value="" maxlength="32" required="" id="id_name">分值：<input type="number" name="score" value="" required="" id="id_score"> <span class="glyphicon glyphicon-remove del_option"></span></p>';
          $(this).parent().children().last().append(s)

    });


    //删除选项事件
    $(document).on('click',".del_option",function () {
        $(this).parent().remove()
    });

    //给保存添加事件

    $("#btn_save").click(function () {
       //循环问题，取出所需数据
    var question_list=[];
    $(".question").each(function () {
        var question_dic={};
        question_dic={"qid":$(this).attr("qid"),"qtitle":$(this).find("#id_caption").val(),
        "qtype":$(this).find(".select_type").val()};

        if ($(this).find(".select_type").val()==2){

            var option_dic={};
            var option_list=[];
            $.each($(this).find(".option"),function () {

                option_dic={"option_id":$(this).attr("option_id"),"option_name":$(this).find("#id_name").val(),
                "option_score":$(this).find("#id_score").val()};
                option_list.push(option_dic)

            });
        }
         question_dic["options"]=option_list;
        question_list.push(question_dic)
    });

    //发送ajax请求，将数据发到后端进行处理
     $.ajax({
         url:"/editor/questionnaire/"+$("#questions").attr("questionnaire_id"),
         type:"POST",
         contentType:"json",
         headers:{"X-CSRFToken":$.cookie('csrftoken')},
         data:JSON.stringify(question_list),
         success:function (data) {

            alert("保存成功")

         }

     })


    })


</script>


</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>首页</title>

    <link rel="stylesheet" href="/static/bootstrap-3.3.7-dist/css/bootstrap.min.css">


</head>
<body>
<h1>问卷调查</h1>

<div class="container">
    <button class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-lg">添加问卷</button>
    <table class="table">
        <thead>
        <tr>
            <th>问卷调查名称</th>
            <th>问卷调查班级</th>
            <th>参与人数</th>
            <th>问卷选项</th>
            <th>调查地址</th>
            <th>查看评分</th>
            <th>操作</th>
        </tr>
        </thead>

        <tbody>
        {% for obj in question_naire_obj %}
            <tr>
                <td>{{ obj.title }}</td>
                <td>{{ obj.cls.title }}</td>
                <td>  {{ obj.count }}/{{ obj.cls.student_set.all.count }}</td>
                <td><a href="/editor/questionnaire/{{ obj.id }}">编辑问卷</a></td>
                <td><a href="/student/evaluate/{{ obj.cls.id }}/{{ obj.id }}">/student/evaluate/{{ obj.cls.id }}/{{ obj.id }}/</a></td>
                <td><a href="">查看评分</a></td>
                <td><a href="">删除</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>


<!-- Large modal -->


<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="container" style="margin-top: 50px">
                <div class="row">
                    <div class="col-md-4 col-md-offset-3">
                        {% csrf_token %}
                        <div class="form-group">
                            <label>问卷调查名&nbsp;&nbsp;&nbsp;：</label><sapn class="title"></sapn>
                            {{ form.title }}
                        </div>
                        <div class="form-group">
                            <label>问卷调查班级：</label><sapn class="cls"></sapn>
                            {{ form.cls }}
                        </div>
                        <div class="form-group">
                            <label>创建人：</label><sapn class="creator"></sapn>
                            {{ form.creator }}
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="add_btn">Save changes</button>
            </div>

        </div>
    </div>
</div>

<script src="/static/jquery-3.2.1.min.js"></script>
<script src="/static/bootstrap-3.3.7-dist/js/bootstrap.min.js"></script>

<script>
    $("#add_btn").click(function () {
        $.ajax({
            url:"/index/",
            type:"POST",
            data:{
                "csrfmiddlewaretoken":$("[name='csrfmiddlewaretoken']").val(),
                "title":$("#id_title").val(),
                "cls":$("#id_cls").val(),
                "creator":$("#id_creator").val()
            },
            success:function (data) {
                $(".title").html('');
                $(".cls").html('');
                $(".creator").html('');
                var data=JSON.parse(data);
                if (data["flag"]){
                    location.href="/index/"
                }
                else {
                   $.each(data["error"],function (i,v) {
                       $('.'+i+'').html(v[0]).css("color","red")
                   })

                }
            }

        })

    })

</script>

</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>登录页面</title>
    <link rel="stylesheet" href="/static/bootstrap-3.3.7-dist/css/bootstrap.min.css">

</head>
<body>

<div class="container">

    <div class="row" style="margin-top: 200px">
        <div class="col-md-4 col-md-offset-4">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">用户名</label>
                <input type="text" id="username" class="form-control" placeholder="请输入用户名">
            </div>
            <div class="form-group">
                <label for="password">密码</label>
                <input type="password" id="password" class="form-control"  placeholder="请输入密码">
            </div>
            <button class="btn btn-primary" id="login_btn">登录</button><span class="error"></span>
        </div>

    </div>

</div>

<script src="/static/jquery-3.2.1.min.js"></script>
<script>
    $("#login_btn").click(function () {
        $.ajax({
            url:"/login/",
            type:"POST",
            data:{
                csrfmiddlewaretoken:$("[name='csrfmiddlewaretoken']").val(),
                username:$("#username").val(),
                password:$("#password").val()
            },
            success:function (data) {
                $(".error").html("");
                var data=JSON.parse(data);
                if (data["flag"]){
                    location.href="/index/"
                }

                else {
                    $(".error").html("用户名密码错误").css("color","red")

                }



            }
        })

    })

</script>

</body>
</html>

templates/question_naire.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
    <link rel="stylesheet" href="/static/bootstrap-3.3.7-dist/css/bootstrap.min.css">
    <style>
        ul{list-style-type:none}
        ul li{display: inline-block;margin-left: 10px;font-size: 20px}
        ul li input{width:20px;height:20px;}
        body{background-color: #ebebeb}
    </style>
</head>
<body>
<h2>请认真填写本次调查问卷</h2>
<h4>1,本班学生只能填写本班的问卷调查。</h4>
<h4>2,一个学生只能对同一个问卷提交一次。</h4>
<div class="container">

    <form action="" method="post" novalidate>
        {% csrf_token %}
       {% for form in forms %}
        <div class="text-justify">
        <h4>{{ forloop.counter }},{{ form.label }} <span style="color: red">{{ form.errors }}</span>  </h4>
        {{ form }}
        </div>
    {% endfor %}

    <input type="submit" value="提交">
    </form>


</div>

</body>
</html>

templates/stu_index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
</head>
<body>
{{ request.session.student_info.stu }}登录成功

</body>
</html>

templates/stu_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>登录页面</title>
    <link rel="stylesheet" href="/static/bootstrap-3.3.7-dist/css/bootstrap.min.css">

</head>
<body>

<div class="container">

    <div class="row" style="margin-top: 200px">
        <div class="col-md-4 col-md-offset-4">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">用户名</label>
                <input type="text" id="username" class="form-control" placeholder="请输入用户名">
            </div>
            <div class="form-group">
                <label for="password">密码</label>
                <input type="password" id="password" class="form-control"  placeholder="请输入密码">
            </div>
            <button class="btn btn-primary" id="login_btn">登录</button><span class="error"></span>
        </div>

    </div>

</div>

<script src="/static/jquery-3.2.1.min.js"></script>
<script>
    $("#login_btn").click(function () {
        $.ajax({
            url:"/stu_login/",
            type:"POST",
            data:{
                csrfmiddlewaretoken:$("[name='csrfmiddlewaretoken']").val(),
                username:$("#username").val(),
                password:$("#password").val()
            },
            success:function (data) {
                $(".error").html("");
                var data=JSON.parse(data);
                if (data["flag"]){
                    location.href="/stu_index/"
                }

                else {
                    $(".error").html("用户名密码错误").css("color","red")

                }



            }
        })

    })

</script>

</body>
</html>